import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata = { title: "Terms of Service — Opaque Studio" };

export default function Terms() {
  return (
    <>
      <Nav />
      <main className="mx-auto max-w-3xl px-5 py-16 leading-relaxed">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted">Last updated: August 17, 2026</p>

        {[
          [
            "1. What Opaque Studio is",
            "Opaque Studio (“the Service”) is a software platform operated by Opaque (“we”, “us”) that lets registered users generate short-form video creatives with AI, manage a content queue, and publish content to third-party social platforms — including TikTok — on accounts the user owns and connects themselves.",
          ],
          [
            "2. Accounts",
            "You need an account to use the Service. You are responsible for your credentials and for everything published from your account. You must be at least 18 years old and provide accurate information. We may suspend accounts that violate these terms or the policies of connected platforms.",
          ],
          [
            "3. Your content",
            "You keep full ownership of the photos you upload, the creatives you generate from them, and the audio you provide. You grant us only the license needed to operate the Service: storing your files, rendering your videos, and transmitting them to platforms you direct us to publish to. You are responsible for having the rights to everything you upload — including music licenses for any audio track you add to a video.",
          ],
          [
            "4. Publishing to TikTok",
            "When you connect a TikTok account, you authorize the Service — through TikTok's official API and subject to TikTok's own consent screens — to upload and publish content to that account when you explicitly request it. Every post requires your action: choosing the creative, the caption, the privacy level, and any commercial content disclosure. We never post without an instruction from you. Your use of TikTok remains governed by TikTok's Terms of Service, Community Guidelines, Branded Content Policy, and Music Usage Confirmation. You can disconnect your TikTok account at any time from your dashboard or from TikTok's app settings, which revokes our access.",
          ],
          [
            "5. Acceptable use",
            "Do not use the Service to publish content that is unlawful, infringing, deceptive, or that violates the rules of the destination platform; to spam or artificially manipulate engagement; or to publish to accounts you do not own or lack authority over. We may remove content or terminate access for violations.",
          ],
          [
            "6. AI-generated output",
            "Creatives are generated by machine-learning models and may contain artifacts or inaccuracies. Review every creative before publishing. You are the publisher of record for content you post.",
          ],
          [
            "7. Fees",
            "The Service is currently in beta and free of charge. Paid plans, when introduced, will be announced in advance and never billed retroactively. Prices shown on the pricing page during beta are indicative.",
          ],
          [
            "8. Termination",
            "You may delete your account at any time (see our Data Deletion page). We may suspend or terminate the Service or your access with reasonable notice, or immediately for material violations.",
          ],
          [
            "9. Disclaimers and liability",
            "The Service is provided “as is” without warranties of any kind. To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages, loss of profits, or loss of data arising from your use of the Service. Our total liability is limited to the amounts you paid us in the twelve months preceding the claim.",
          ],
          [
            "10. Changes",
            "We may update these terms; material changes will be announced on this page and, for registered users, by email. Continued use after changes take effect constitutes acceptance.",
          ],
          [
            "11. Contact",
            "Questions about these terms: nicolle.aurelien@gmail.com.",
          ],
        ].map(([h, b]) => (
          <section key={h} className="mt-8">
            <h2 className="text-lg font-semibold">{h}</h2>
            <p className="mt-2 text-muted">{b}</p>
          </section>
        ))}
      </main>
      <Footer />
    </>
  );
}
